
# cities = ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"]
cities = [
  "San Francisco",
  "Athens",
  "Kalabaka",
  "Corfu",
  "Catania",
  "Naples",
  "Pisa",
  "Marseille",
  "Barcelona",
  "Porto",
  "Lisbon",
  "Lagos",
  "Sagres",
  "Albufeira",
  "Faro",
  "Marrakesh",
  "Taghazout",
  "Merzouga",
  "Marrakesh",
  "London",
  "Amsterdam",
  "Hamburg",
  "Copenhagen",
  "Berlin",
  "Munich",
  "Vienna",
  "Prague",
  "Vienna",
  "Budapest",
  # "krakow",
]
