# [[cities]]
# city = "San Francisco"
# country = "USA"

[[cities]]
city = "Athens"
country = "Greece"

[[cities]]
city = "Kalabaka"
country = "Greece"

[[cities]]
city = "Corfu"
country = "Greece"

[[cities]]
city = "Catania"
country = "Italy"

[[cities]]
city = "Naples"
country = "Italy"

[[cities]]
city = "Pisa"
country = "Italy"

[[cities]]
city = "Marseille"
country = "France"

[[cities]]
city = "Barcelona"
country = "Spain"

[[cities]]
city = "Porto"
country = "Portugal"

[[cities]]
city = "Lisbon"
country = "Portugal"

[[cities]]
city = "Lagos"
country = "Portugal"

[[cities]]
city = "Sagres"
country = "Portugal"

[[cities]]
city = "Albufeira"
country = "Portugal"

[[cities]]
city = "Faro"
country = "Portugal"

[[cities]]
city = "Marrakesh"
country = "Morocco"

[[cities]]
city = "Taghazout"
country = "Morocco"

[[cities]]
city = "Merzouga"
country = "Morocco"

[[cities]]
city = "Marrakesh"
country = "Morocco" # Duplicated entry

[[cities]]
city = "London"
country = "United Kingdom"

[[cities]]
city = "Amsterdam"
country = "Netherlands"

[[cities]]
city = "Hamburg"
country = "Germany"

[[cities]]
city = "Copenhagen"
country = "Denmark"

[[cities]]
city = "Berlin"
country = "Germany"

[[cities]]
city = "Munich"
country = "Germany"

[[cities]]
city = "Vienna"
country = "Austria"

[[cities]]
city = "Prague"
country = "Czech Republic"

[[cities]]
city = "Vienna"
country = "Austria" # Duplicated entry

[[cities]]
city = "Budapest"
country = "Hungary"

[[cities]]
city = "Krakow"
country = "Poland"

[[cities]]
city = "Warsaw"
country = "Poland"

[[cities]]
city = "Bangkok"
country = "Thailand"

[[cities]]
city = "phuket"
country = "Thailand"

[[cities]]
city = "ko phi phi don"
country = "Thailand"

# krabi
[[cities]]
city = "กระบี่"
country = "Thailand"

[[cities]]
city = "ko phangan"
country = "Thailand"

[[cities]]
city = "ko tao"
country = "Thailand"

[[cities]]
city = "ko samui"
country = "Thailand"

[[cities]]
city = "Chiang mai"
country = "Thailand"

[[cities]]
city = "Ho Chi Minh City"
country = "Vietnam"

[[cities]]
city = "Bao Loc"
country = "Vietnam"

[[cities]]
city = "Dalat"
country = "Vietnam"

[[cities]]
city = "Nha Trang"
country = "Vietnam"

[[cities]]
city = "Da Nang"
country = "Vietnam"

[[cities]]
city = "Phong Nha"
country = "Vietnam"
