[[coordinates]]
city = "Athens"
latitude = 37.9755648
longitude = 23.7348324

[[coordinates]]
city = "Kalabaka"
latitude = 39.7070178
longitude = 21.6279431

[[coordinates]]
city = "Corfu"
latitude = 39.591337
longitude = 19.859618918733858

[[coordinates]]
city = "Catania"
latitude = 37.5023612
longitude = 15.0873718

[[coordinates]]
city = "Naples"
latitude = 40.8358846
longitude = 14.2487679

[[coordinates]]
city = "Pisa"
latitude = 43.4714722
longitude = 10.679791173704576

[[coordinates]]
city = "Marseille"
latitude = 43.2961743
longitude = 5.3699525

[[coordinates]]
city = "Barcelona"
latitude = 41.3828939
longitude = 2.1774322

[[coordinates]]
city = "Porto"
latitude = 41.1494512
longitude = -8.6107884

[[coordinates]]
city = "Lisbon"
latitude = 38.7077507
longitude = -9.1365919

[[coordinates]]
city = "Lagos"
latitude = 37.1027964
longitude = -8.6728689

[[coordinates]]
city = "Sagres"
latitude = 37.0078288
longitude = -8.941924

[[coordinates]]
city = "Albufeira"
latitude = 37.088241
longitude = -8.2526339

[[coordinates]]
city = "Faro"
latitude = 37.0162727
longitude = -7.9351771

[[coordinates]]
city = "Marrakesh"
latitude = 31.6258257
longitude = -7.9891608

[[coordinates]]
city = "Taghazout"
latitude = 30.544722
longitude = -9.709128

[[coordinates]]
city = "Merzouga"
latitude = 31.0999166
longitude = -4.0140878

[[coordinates]]
city = "Marrakesh"
latitude = 31.6258257
longitude = -7.9891608

[[coordinates]]
city = "London"
latitude = 51.4893335
longitude = -0.14405508452768728

[[coordinates]]
city = "Amsterdam"
latitude = 52.3730796
longitude = 4.8924534

[[coordinates]]
city = "Hamburg"
latitude = 53.550341
longitude = 10.000654

[[coordinates]]
city = "Copenhagen"
latitude = 55.6867243
longitude = 12.5700724

[[coordinates]]
city = "Berlin"
latitude = 52.510885
longitude = 13.3989367

[[coordinates]]
city = "Munich"
latitude = 48.1371079
longitude = 11.5753822

[[coordinates]]
city = "Vienna"
latitude = 48.2083537
longitude = 16.3725042

[[coordinates]]
city = "Prague"
latitude = 50.0874654
longitude = 14.4212535

[[coordinates]]
city = "Vienna"
latitude = 48.2083537
longitude = 16.3725042

[[coordinates]]
city = "Budapest"
latitude = 47.48138955
longitude = 19.14609412691246

[[coordinates]]
city = "Krakow"
latitude = 50.0619474
longitude = 19.9368564

[[coordinates]]
city = "Warsaw"
latitude = 52.2337172
longitude = 21.071432235636493

[[coordinates]]
city = "Bangkok"
latitude = 13.7524938
longitude = 100.4935089

[[coordinates]]
city = "phuket"
latitude = 7.9366015
longitude = 98.3529292

[[coordinates]]
city = "ko phi phi don"
latitude = 7.7522403
longitude = 98.77664336667435

[[coordinates]]
city = "กระบี่"
latitude = 8.0634637
longitude = 98.9162345

[[coordinates]]
city = "ko phangan"
latitude = 9.734950300000001
longitude = 100.0305710845208

[[coordinates]]
city = "ko tao"
latitude = 10.0921822
longitude = 99.83953617562148

[[coordinates]]
city = "ko samui"
latitude = 9.5071545
longitude = 99.9957562

[[coordinates]]
city = "Chiang mai"
latitude = 18.7882778
longitude = 98.9858802

[[coordinates]]
city = "Ho Chi Minh City"
latitude = 10.7763897
longitude = 106.7011391

[[coordinates]]
city = "Bao Loc"
latitude = 11.5506941
longitude = 107.8092511

[[coordinates]]
city = "Dalat"
latitude = 11.9402416
longitude = 108.4375758

[[coordinates]]
city = "Nha Trang"
latitude = 12.2431693
longitude = 109.1898675

[[coordinates]]
city = "Da Nang"
latitude = 16.068
longitude = 108.212

[[coordinates]]
city = "Phong Nha"
latitude = 17.6069708
longitude = 106.3026134

[[coordinates]]
city = "vinh"
latitude = 18.6698528
longitude = 105.6840371

[[coordinates]]
city = "mai chau"
latitude = 20.71587505
longitude = 104.97912930663392

[[coordinates]]
city = "Hanoi"
latitude = 21.0283334
longitude = 105.854041

[[coordinates]]
city = "taipei"
latitude = 25.0375198
longitude = 121.5636796

[[coordinates]]
city = "Taoyuan"
latitude = 24.9929995
longitude = 121.3010003

[[coordinates]]
city = "Hsinchu"
latitude = 24.8066333
longitude = 120.9686833

[[coordinates]]
city = "Taichung"
latitude = 24.163162
longitude = 120.6478282

[[coordinates]]
city = "Chayi"
latitude = 23.4592368
longitude = 120.3237915

[[coordinates]]
city = "Kaohsiung"
latitude = 22.6203348
longitude = 120.3120375

[[coordinates]]
city = "Checheng"
latitude = 22.0739455
longitude = 120.714193

[[coordinates]]
city = "Taitung"
latitude = 22.7553667
longitude = 121.1506

[[coordinates]]
city = "taipei"
latitude = 25.0375198
longitude = 121.5636796

[[coordinates]]
city = "Seoul"
latitude = 37.5666791
longitude = 126.9782914

[[coordinates]]
city = "Fukuoka"
latitude = 33.6251241
longitude = 130.6180016

