# [[coordinates]]
# city = "San Francisco"
# latitude = 37.7792588
# longitude = -122.4193286
#
[[coordinates]]
city = "Athens"
latitude = 37.9755648
longitude = 23.7348324

[[coordinates]]
city = "Kalabaka"
latitude = 39.7070178
longitude = 21.6279431

[[coordinates]]
city = "Corfu"
latitude = 39.591337
longitude = 19.859618918733858

[[coordinates]]
city = "Catania"
latitude = 37.5023612
longitude = 15.0873718

[[coordinates]]
city = "Naples"
latitude = 40.8358846
longitude = 14.2487679

[[coordinates]]
city = "Pisa"
latitude = 43.4714722
longitude = 10.679791173704576

[[coordinates]]
city = "Marseille"
latitude = 43.2961743
longitude = 5.3699525

[[coordinates]]
city = "Barcelona"
latitude = 41.3828939
longitude = 2.1774322

[[coordinates]]
city = "Porto"
latitude = 41.1494512
longitude = -8.6107884

[[coordinates]]
city = "Lisbon"
latitude = 38.7077507
longitude = -9.1365919

[[coordinates]]
city = "Lagos"
latitude = 37.1027964
longitude = -8.6728689

[[coordinates]]
city = "Sagres"
latitude = 37.0078288
longitude = -8.941924

[[coordinates]]
city = "Albufeira"
latitude = 37.088241
longitude = -8.2526339

[[coordinates]]
city = "Faro"
latitude = 37.0162727
longitude = -7.9351771

[[coordinates]]
city = "Marrakesh"
latitude = 31.6258257
longitude = -7.9891608

[[coordinates]]
city = "Taghazout"
latitude = 30.544722
longitude = -9.709128

[[coordinates]]
city = "Merzouga"
latitude = 31.0999166
longitude = -4.0140878

[[coordinates]]
city = "Marrakesh"
latitude = 31.6258257
longitude = -7.9891608

[[coordinates]]
city = "London"
latitude = 51.5074456
longitude = -0.1277653

[[coordinates]]
city = "Amsterdam"
latitude = 52.3730796
longitude = 4.8924534

[[coordinates]]
city = "Hamburg"
latitude = 53.550341
longitude = 10.000654

[[coordinates]]
city = "Copenhagen"
latitude = 55.6867243
longitude = 12.5700724

[[coordinates]]
city = "Berlin"
latitude = 52.5108638
longitude = 13.3989421

[[coordinates]]
city = "Munich"
latitude = 48.1371079
longitude = 11.5753822

[[coordinates]]
city = "Vienna"
latitude = 48.2083537
longitude = 16.3725042

[[coordinates]]
city = "Prague"
latitude = 50.0874654
longitude = 14.4212535

[[coordinates]]
city = "Vienna"
latitude = 48.2083537
longitude = 16.3725042

[[coordinates]]
city = "Budapest"
latitude = 47.4978789
longitude = 19.0402383
